name: Go

on:
  push:
    branches: [ master ]
  pull_request:

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.41

    - name: Build
      run: |
        make get
        make build

    - name: Unit Test
      run: make test

    - name: Scenario Test
      run: make scenario-test
