name: Release

on:
  pull_request:
  #  push:
  #    branches: [ master ]
  #    paths: ['CHANGELOG.md']

jobs:

  build:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v2

    - name: Extract Version
      id: version
      run: |
        VERSION=$(head -1 CHANGELOG.md | sed -e 's/^.*Version //g')
        echo "$VERSION"
        git fetch --prune --unshallow
        PRETAG=$(git describe --tags --abbrev=0)
        echo "$PRETAG"
        CHANGELOG=$(git diff $PRETAG..${{ github.sha }} CHANGELOG.md | grep -E '^\+' | grep -v '+++' | sed -e 's/^\+//g')
        echo "$CHANGELOG"
        echo ::set-output name=version::$VERSION
        echo ::set-output name=changelog::$CHANGELOG

        #     - name: Tag
        #       id: tag_version
        #       uses: mathieudutour/github-tag-action@v5.2
        #       with:
        #         custom_tag: ${{ steps.version.outputs.version }}
        #         github_token: ${{ secrets.GITHUB_TOKEN }}
        # 
        #     - name: Release
        #       uses: softprops/action-gh-release@v1
        #       with:
        #         files: |
        #           CHANGELOG.md
        #           LICENSE
        #         tag_name: ${{ steps.tag_version.outputs.new_tag }}
        #         body_path: tmp-changelog.txt
        #       env:
        #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
